# Generated by Django 4.0.5 on 2022-06-30 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Venue', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(default='get pesa guide', max_length=200)),
                ('description', models.TextField()),
                ('type', models.TextField()),
                ('created_at', models.DateField(verbose_name=datetime.date(2022, 6, 30))),
                ('date', models.DateField()),
                ('time_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('event', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
            ],
        ),
    ]
