# Generated by Django 4.0.5 on 2022-06-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_appusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUsers',
            new_name='AppUser',
        ),
    ]
