# Generated by Django 4.0.5 on 2022-06-30 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_appusers_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
