# Generated by Django 4.0.5 on 2022-07-01 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rsvp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateField(verbose_name=datetime.date(2022, 7, 1)),
        ),
    ]
