# Generated by Django 4.0.5 on 2022-07-11 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_appuser_role_alter_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateField(verbose_name=datetime.date(2022, 7, 11)),
        ),
    ]
