# Generated by Django 4.0.5 on 2022-07-11 17:58

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_banner_alter_event_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.upload_to),
        ),
    ]
